Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/10/2023
Var
// Seção de Declarações das variáveis 

// Enquanto, Se, Para,
a: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

leia (a)
   Se a %  2= 0 então
      escreva ("O número " ,a, " é par")

   senão
        escreva ("O número " ,a, " é impar")
   fimse

Fimalgoritmo