Algoritmo "multiplos de 3 e 7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2023
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i <- 3 ate 300 faça
        se (i mod 3 = 0) ou (i mod 7 = 0) entao
           escreva (i)
        fimse
   fimpara

Fimalgoritmo